apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: dolldot/emoh-web:develop
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_HOST
              value: '0.0.0.0'
            - name: NUXT_PORT
              value: '3000'
            - name: API_URL
              value: 'server-cluster-ip-service'
